image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - git clone https://github.com/openSUSE/docker-containers-build.git brew --depth 1 -b openSUSE-42.1


clone_leap:
  script:
    - docker pull opensuse:42.1
    - docker tag opensuse:42.1 registry.gitlab.com/gbraad/opensuse:42.1
    - docker push registry.gitlab.com/gbraad/opensuse:42.1
  only:
    - master

clone_tumbleweed:
  script:
    - docker pull opensuse:tumbleweed
    - docker tag opensuse:tumbleweed registry.gitlab.com/gbraad/opensuse:tumbleweed
    - docker push registry.gitlab.com/gbraad/opensuse:tumbleweed
  only:
    - master

build_base:
  script:
    - docker build -t registry.gitlab.com/gbraad/opensuse:brew ./brew/docker/
    - docker push registry.gitlab.com/gbraad/opensuse:brew
  only:
    - master

